server:
  port: 8095

feign-client:
  serverUrl: http://localhost:8080

cron:
  value: 0 0/10 * * * ?

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  datasource:
    username: root
    password: test
    url: jdbc:mariadb://localhost:3308/test
